Repository InvoiceShelf/InvoiceShelf, pull requests merged in 2024-11, with the labels that each got.

#217 New Crowdin updates
  lang/ja.json
Labels: enhancement

#215 chore: Update Issue Template
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/ISSUE_TEMPLATE/code_quality_issue.yml
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/feature_request.yml
Labels: documentation

#214 feat(infrastructure): improve htaccess configuration.
  public/.htaccess
Labels: enhancement

#221 New Crowdin updates
  lang/el.json
  lang/sv.json
Labels: enhancement

#225 New Crowdin updates
  lang/fr.json
  lang/hr.json
  lang/ru.json
  lang/sv.json
Labels: crowdin
