Repository InvoiceShelf/InvoiceShelf, pull requests merged in 2025-08, with the labels that each got.

#224 fix(csrf-token): add leading dot to session domain cookie.
  .env.example
  app/Http/Controllers/V1/Installation/DatabaseConfigurationController.php
  app/Space/EnvironmentManager.php
  composer.lock
  config/sanctum.php
  package.json
  resources/scripts/admin/stores/installation.js
  resources/scripts/admin/views/installation/Step4VerifyDomain.vue
  resources/scripts/admin/views/installation/database/MysqlDatabase.vue
  resources/scripts/admin/views/installation/database/PgsqlDatabase.vue
  resources/scripts/admin/views/installation/database/SqliteDatabase.vue
  resources/scripts/plugins/axios.js
  routes/web.php
Labels: code quality

#399 fixed czech translations
  lang/cs.json
Labels: crowdin

#395 Add Algerian Dinar (DZD) currency support
  database/seeders/CurrenciesTableSeeder.php
Labels: enhancement, enhancement: UX

#398 Fixed deprecated i18n api
  resources/scripts/admin/stores/customer.js
  resources/scripts/admin/stores/estimate.js
  resources/scripts/admin/stores/expense.js
  resources/scripts/admin/stores/invoice.js
  resources/scripts/admin/stores/item.js
  resources/scripts/admin/stores/payment.js
  resources/scripts/admin/stores/users.js
Labels: code quality

#385 fix: Create item with tax (ItemModal)
  resources/scripts/admin/components/modal-components/ItemModal.vue
Labels: bug

#403 Fix: Use amounts in base currency for customer charts
  app/Http/Controllers/V1/Admin/Customer/CustomerStatsController.php
Labels: code quality

#183 chore: Update dockerfile for dev and prod
  .dev/Dockerfile
  .dev/README.md
  .dev/docker-compose.mysql.yml
  .dev/docker-compose.pgsql.yml
  .dev/docker-compose.sqlite.yml
  .dev/nginx.Dockerfile
  .dev/nginx/conf.d/dev.conf
  .dev/php.ini
  .dev/php/Dockerfile
  .dev/php/entrypoint.sh
  .dockerignore
  package.json
  tailwind.config.js
  vite.config.js
  yarn.lock
Labels: enhancement

#439 Fix: Weird gap in invoice items description
  resources/views/app/pdf/invoice/invoice1.blade.php
  resources/views/app/pdf/invoice/invoice2.blade.php
  resources/views/app/pdf/invoice/invoice3.blade.php
Labels: code quality, enhancement: UI
