Repository InvoiceShelf/InvoiceShelf, pull requests merged in 2025-01, with the labels that each got.

#241 New Crowdin updates
  lang/ar.json
  lang/cs.json
  lang/de.json
  lang/es.json
  lang/fr.json
  lang/id.json
  lang/ja.json
  lang/nl.json
  lang/pt.json
  lang/sk.json
Labels: crowdin

#144 refactor: Update file paths for stub files for module creation & add name to base admin-route
  config/modules.php
  resources/scripts/admin/admin-router.js
Labels: code quality

#222 fix: Corrects and simplifies password visibility icon logic.
  resources/scripts/admin/components/modal-components/CustomerModal.vue
  resources/scripts/admin/views/auth/Login.vue
  resources/scripts/admin/views/customers/Create.vue
  resources/scripts/admin/views/installation/Step6AccountSettings.vue
  resources/scripts/admin/views/installation/mail-driver/MailgunMailDriver.vue
  resources/scripts/admin/views/installation/mail-driver/SesMailDriver.vue
  resources/scripts/admin/views/installation/mail-driver/SmtpMailDriver.vue
  resources/scripts/admin/views/settings/mail-driver/MailgunMailDriver.vue
  resources/scripts/admin/views/settings/mail-driver/SesMailDriver.vue
  resources/scripts/admin/views/settings/mail-driver/SmtpMailDriver.vue
  resources/scripts/customer/views/auth/Login.vue
  resources/scripts/customer/views/auth/ResetPassword.vue
  resources/scripts/customer/views/settings/CustomerSettings.vue
Labels: enhancement

#227 fix: update company info on array of companies.
  resources/scripts/admin/stores/company.js
Labels: code quality

#247 FIX : Adding `sent` and `viewed` field to payload #240
  app/Http/Requests/InvoicesRequest.php
Labels: code quality

#248 Add Amount Paid and Amount Due to Invoice PDF
  lang/en.json
  resources/views/app/pdf/invoice/partials/table.blade.php
Labels: enhancement

#258 Update TND Currency
  database/seeders/CurrenciesTableSeeder.php
Labels: code quality, crowdin
