Repository InvoiceShelf/InvoiceShelf, pull requests merged in 2025-05, with the labels that each got.

#347 Fix security alert on axios 0.29
  package.json
Labels: code quality

#184 Feat(Gotenberg): Opt-in alternative pdf generation for modern CSS
  .dev/docker-compose.mysql.yml
  .dev/docker-compose.pgsql.yml
  .dev/docker-compose.sqlite.yml
  .env.example
  app/Facades/PDF.php
  app/Http/Controllers/V1/Admin/Settings/PDFConfigurationController.php
  app/Http/Requests/PDFConfigurationRequest.php
  app/Models/Estimate.php
  app/Models/Invoice.php
  app/Policies/SettingsPolicy.php
  app/Providers/AppServiceProvider.php
  app/Providers/PDFServiceProvider.php
  app/Services/PDFDrivers/GotenbergPDFDriver.php
  app/Services/PDFService.php
  app/Space/EnvironmentManager.php
  bootstrap/providers.php
  composer.json
  composer.lock
  config/invoiceshelf.php
  config/pdf.php
  lang/en.json
  resources/scripts/admin/admin-router.js
  resources/scripts/admin/stores/pdf-driver.js
  resources/scripts/admin/views/settings/PDFGenerationSetting.vue
  resources/scripts/admin/views/settings/pdf-driver/DomPDFDriver.vue
  resources/scripts/admin/views/settings/pdf-driver/GotenbergDriver.vue
  routes/api.php
Labels: enhancement

#253 Adding Flat Tax support with fixed amount
  app/Http/Requests/TaxTypeRequest.php
  app/Http/Resources/TaxResource.php
  app/Http/Resources/TaxTypeResource.php
  app/Models/Invoice.php
  app/Models/Tax.php
  app/Models/TaxType.php
  database/factories/TaxTypeFactory.php
  database/migrations/2024_12_11_102055_update_taxes_to_handle_fixed_amount.php
  lang/en.json
  resources/scripts/admin/components/estimate-invoice-common/CreateItemRowTax.vue
  resources/scripts/admin/components/estimate-invoice-common/CreateTotal.vue
  resources/scripts/admin/components/estimate-invoice-common/CreateTotalTaxes.vue
  resources/scripts/admin/components/estimate-invoice-common/SelectTaxPopup.vue
  resources/scripts/admin/components/modal-components/ItemModal.vue
  resources/scripts/admin/components/modal-components/TaxTypeModal.vue
  resources/scripts/admin/stores/tax-type.js
  resources/scripts/admin/views/items/Create.vue
  resources/scripts/admin/views/settings/TaxTypesSetting.vue
  resources/views/app/pdf/estimate/partials/table.blade.php
  resources/views/app/pdf/invoice/partials/table.blade.php
  tests/Feature/Admin/ItemTest.php
  tests/Feature/Admin/TaxTypeTest.php
Labels: enhancement

#345 New Crowdin updates
  lang/ar.json
  lang/bg.json
  lang/cs.json
  lang/de.json
  lang/el.json
  lang/es.json
  lang/fa.json
  lang/fi.json
  lang/fr.json
  lang/hi.json
  lang/hr.json
  lang/id.json
  lang/it.json
  lang/ja.json
  lang/lt.json
  lang/lv.json
  lang/mk.json
  lang/nl.json
  lang/pl.json
  lang/pt.json
  lang/ro.json
  lang/ru.json
  lang/sk.json
  lang/sl.json
  lang/sr.json
  lang/sv.json
  lang/th.json
  lang/tr.json
  lang/uk.json
  lang/vi.json
  lang/zh.json
Labels: crowdin

#346 Upgrading to Laravel 12
  composer.json
  composer.lock
  config/backup.php
  config/filesystems.php
Labels: code quality

#278 Improving github workflow
  .github/workflows/check.yaml
Labels: CI/CD

#377 fix: Create item with tax
  resources/scripts/admin/views/items/Create.vue
Labels: bug, code quality
