Repository InvoiceShelf/InvoiceShelf, pull requests merged in 2025-04, with the labels that each got.

#320 Fix: Capitalise 'date' in invoice due date label
  lang/en.json
Labels: code quality

#341 306 update GitHub issuepr templates
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/ISSUE_TEMPLATE/code_quality_issue.yml
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/feature_request.yml
  .github/PULL_REQUEST_TEMPLATE/pull_request_template.md
Labels: code quality

#335 Fix negative values on item price
  database/migrations/2025_03_15_160016_allow_unsigned_item_price.php
  resources/scripts/admin/components/estimate-invoice-common/CreateItemRow.vue
Labels: bug

#280 Checking version number on version.md file
  app/Console/Commands/UpdateCommand.php
  app/Http/Controllers/AppVersionController.php
  app/Http/Controllers/V1/Admin/Update/CheckVersionController.php
Labels: code quality

#263 feat: default notes
  app/Http/Controllers/V1/Admin/General/NotesController.php
  app/Http/Requests/NotesRequest.php
  app/Http/Resources/NoteResource.php
  database/factories/NoteFactory.php
  database/migrations/2025_01_05_211404_add_is_default_to_notes_table.php
  lang/de.json
  lang/en.json
  resources/scripts/admin/components/modal-components/NoteModal.vue
  resources/scripts/admin/stores/estimate.js
  resources/scripts/admin/stores/invoice.js
  resources/scripts/admin/stores/note.js
  resources/scripts/admin/stores/payment.js
  resources/scripts/admin/stores/recurring-invoice.js
  resources/scripts/admin/views/invoices/create/InvoiceCreate.vue
  resources/scripts/admin/views/settings/NotesSetting.vue
  tailwind.config.js
Labels: enhancement
